name: test
on:
  workflow_dispatch:

jobs:
  update-posts:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to federate tokens
      contents: read # needed to check out the website repo

    steps:
      - name: Federate token from Octo STS
        uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: test-organization-fabz/test-octo-sts-destination
          identity: update-readme

      # this uses GITHUB_TOKEN, the built-in short-lived token for this repo only
      - name: Checkout website repo 
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: website

      # this uses the token we asked for to interact with this repo only
      - name: Checkout profile repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: test-organization-fabz/test-octo-sts-destination
          path: profile
          token: ${{ steps.octo-sts.outputs.token }}